version: '3.1'

services:

  web:
    image: nginx
    volumes:
      - /nginx:/etc/nginx/conf.d/
    ports:
      - "8888:80"
    environment:
      - NGINX_PORT=80
    command: [nginx-debug, '-g', 'daemon off;']

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - /wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /db:/var/lib/mysql

